### ISSUE TITLE
apiutil のリクエスト送信を簡易なものにして良いと思う

### ISSUE THREAD

**Issue by retlat** [ww2or3ww/covid19_shizuoka-opendata_csv2json-go#1]
HTTP リクエストがシンプルなので [http.Get()](https://golang.org/pkg/net/http/#Get) を使うことで十分なように思う
https://github.com/ww2or3ww/covid19_shizuoka-opendata_csv2json-go/blob/19666db9f33fd7745de90dead15f1e5ac61b1abb/src/app/utils/apiutil/apiutil.go#L13-L21

**Comment by ww2or3ww** [comment]
@retlat ありがとうございました。
#1 #2 #3 これら対応して、mainへマージまで行いました。Issueも閉じておきます。
