### ISSUE TITLE
interface{} から string への変換は不要ではないか

### ISSUE THREAD

**Issue by retlat** [ww2or3ww/covid19_shizuoka-opendata_csv2json-go#2]
どの case も不要で `fmt.Sprintf("%s", data)` があれば良いように思う
https://github.com/ww2or3ww/covid19_shizuoka-opendata_csv2json-go/blob/19666db9f33fd7745de90dead15f1e5ac61b1abb/src/app/utils/logger/logger.go#L85-L90

**Comment by ww2or3ww** [comment]
ありがとうございました。
