### ISSUE TITLE
変数の初期化に問題があり panic が発生する可能性がある

### ISSUE THREAD

**Issue by retlat** [ww2or3ww/covid19_shizuoka-opendata_csv2json-go#3]
変数が zero value の nil になっているため、 for loop の処理によっては 81 行目で panic が発生する
https://github.com/ww2or3ww/covid19_shizuoka-opendata_csv2json-go/blob/19666db9f33fd7745de90dead15f1e5ac61b1abb/src/app/csv2json/csv2json.go#L30

以下のように初期化するのが好ましい
```diff
- var mapResult map[string]interface{}
+ mapResult := make(map[string]interface{})
```

**Comment by ww2or3ww** [comment]
ありがとうございました。
