### ISSUE TITLE
json のデコード、エンコードに改善の余地がある

### ISSUE THREAD

**Issue by retlat** [ww2or3ww/covid19_shizuoka-opendata_csv2json-go#4]
型が決められるのであれば型を宣言し、 json の [Decode()](https://golang.org/pkg/encoding/json/#Decoder.Decode) や [Marshal()](https://golang.org/pkg/encoding/json/#Marshal) を活用すると良いと思う

**Comment by ww2or3ww** [comment]
issue 1-3 同様、対応してマージまで行いましたので、ひとまずこちらもCloseしておきます。
もし何か気になるところなどありましたら、ぜひコメントお願いします！
ありがとうございました！
